import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PageNavBar } from "@/components/ui/pageNavBar";
import { QueryProvider } from "@/components/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black`}
      >
        <QueryProvider>
          <header className="w-full max-w-3xl mx-auto py-2">
            <PageNavBar />
          </header>
          <div className="flex flex-col w-full max-w-3xl mx-auto p-4">
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
